# states.py
USER_STATE = {}
USER_CONTEXT = {}

ADD_PROJECT_NAME = "ADD_PROJECT_NAME"
ADD_PROJECT_CUSTOMER = "ADD_PROJECT_CUSTOMER"

EDIT_PROJECT_CHOOSE_FIELD = "EDIT_PROJECT_CHOOSE_FIELD"
EDIT_PROJECT_NEW_VALUE = "EDIT_PROJECT_NEW_VALUE"
